[package]
name = "actix_type_handler"
version = "0.1.0"
edition = "2018"

[dependencies]
proc-macro2 = "1.0.60"
quote = "1.0.28"
# syn = {version="2.0.18", feature=["full"]}
syn = { version = "1.0.98", features = ["full"] }
[lib]
proc-macro = true

